import type { ComponentType } from 'react'
import type { AppIconProps } from './base'
import type { IconPaletteName } from './palettes'
import {
  AlertIcon,
  ArrowRightIcon,
  BanIcon,
  BellIcon,
  CalendarIcon,
  CalendarViewIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ClockIcon,
  ConfirmedStatusIcon,
  DownloadIcon,
  FilterIcon,
  HeartIcon,
  HomeIcon,
  InfoIcon,
  InviteIcon,
  LightbulbIcon,
  ListViewIcon,
  MapPinIcon,
  MapViewIcon,
  MenuIcon,
  MessageIcon,
  PencilIcon,
  PlusIcon,
  RepeatIcon,
  SearchIcon,
  ShareIcon,
  SortIcon,
  StarIcon,
  SummerPlansMarkIcon,
  SunIcon,
  TagIcon,
  TentativeStatusIcon,
  TrashIcon,
  UserIcon,
  UsersIcon,
  XIcon,
} from './system-icons'
import {
  BeachDayIcon,
  BbqIcon,
  BikeRideIcon,
  BoardGamesIcon,
  BoatingIcon,
  BonfireIcon,
  CampingIcon,
  CoffeeDateIcon,
  ConcertIcon,
  FarmersMarketIcon,
  FishingIcon,
  GameNightIcon,
  GolfIcon,
  HikingIcon,
  IceCreamIcon,
  KayakingIcon,
  LakeBoatHangoutIcon,
  LakeDayIcon,
  LakePlankRaftIcon,
  MovieNightIcon,
  MuseumsIcon,
  PickleballIcon,
  PicnicIcon,
  PizzaAndDrinksIcon,
  PoolDayIcon,
  RoadTripIcon,
  StargazingIcon,
  SunsetWatchIcon,
  SurfingIcon,
  TennisIcon,
  VolleyballIcon,
  WaterParkIcon,
} from './activity-icons'

type IconComponent = ComponentType<AppIconProps>

export type AppIconKind = 'system' | 'scene'
export type AppIconFamily = 'brand' | 'navigation' | 'planning' | 'views' | 'actions' | 'status' | 'activity' | 'utility'

export type AppIconDefinition = {
  label: string
  component: IconComponent
  family: AppIconFamily
  kind: AppIconKind
  defaultPalette: IconPaletteName
}

export const ICON_REGISTRY = {
  summerPlansMark: { label: 'Summer Plans', component: SummerPlansMarkIcon, family: 'brand', kind: 'scene', defaultPalette: 'brand' },
  sun: { label: 'Today', component: SunIcon, family: 'brand', kind: 'scene', defaultPalette: 'brand' },
  bell: { label: 'Notifications', component: BellIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  plus: { label: 'Add', component: PlusIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  arrowRight: { label: 'Arrow Right', component: ArrowRightIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  chevronRight: { label: 'Chevron Right', component: ChevronRightIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  chevronLeft: { label: 'Chevron Left', component: ChevronLeftIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  chevronDown: { label: 'Chevron Down', component: ChevronDownIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  home: { label: 'Home', component: HomeIcon, family: 'navigation', kind: 'system', defaultPalette: 'mono' },
  calendar: { label: 'Plans', component: CalendarIcon, family: 'navigation', kind: 'system', defaultPalette: 'mono' },
  lightbulb: { label: 'Ideas', component: LightbulbIcon, family: 'navigation', kind: 'system', defaultPalette: 'mono' },
  user: { label: 'Me', component: UserIcon, family: 'navigation', kind: 'system', defaultPalette: 'mono' },
  people: { label: 'People', component: UsersIcon, family: 'navigation', kind: 'system', defaultPalette: 'mono' },
  messages: { label: 'Messages', component: MessageIcon, family: 'navigation', kind: 'system', defaultPalette: 'mono' },
  more: { label: 'More', component: MenuIcon, family: 'navigation', kind: 'system', defaultPalette: 'mono' },
  time: { label: 'Time', component: ClockIcon, family: 'planning', kind: 'system', defaultPalette: 'mono' },
  repeat: { label: 'Repeat', component: RepeatIcon, family: 'planning', kind: 'system', defaultPalette: 'mono' },
  category: { label: 'Category', component: TagIcon, family: 'planning', kind: 'system', defaultPalette: 'mono' },
  location: { label: 'Location', component: MapPinIcon, family: 'planning', kind: 'system', defaultPalette: 'mono' },
  listView: { label: 'List View', component: ListViewIcon, family: 'views', kind: 'system', defaultPalette: 'mono' },
  calendarView: { label: 'Calendar View', component: CalendarViewIcon, family: 'views', kind: 'system', defaultPalette: 'mono' },
  filter: { label: 'Filter', component: FilterIcon, family: 'views', kind: 'system', defaultPalette: 'mono' },
  search: { label: 'Search', component: SearchIcon, family: 'views', kind: 'system', defaultPalette: 'mono' },
  sort: { label: 'Sort', component: SortIcon, family: 'views', kind: 'system', defaultPalette: 'mono' },
  mapView: { label: 'Map View', component: MapViewIcon, family: 'views', kind: 'system', defaultPalette: 'mono' },
  edit: { label: 'Edit', component: PencilIcon, family: 'actions', kind: 'system', defaultPalette: 'mono' },
  delete: { label: 'Delete', component: TrashIcon, family: 'actions', kind: 'system', defaultPalette: 'mono' },
  share: { label: 'Share', component: ShareIcon, family: 'actions', kind: 'system', defaultPalette: 'mono' },
  invite: { label: 'Invite', component: InviteIcon, family: 'actions', kind: 'system', defaultPalette: 'mono' },
  export: { label: 'Export', component: DownloadIcon, family: 'actions', kind: 'system', defaultPalette: 'mono' },
  save: { label: 'Save', component: HeartIcon, family: 'actions', kind: 'system', defaultPalette: 'mono' },
  confirmed: { label: 'Confirmed', component: ConfirmedStatusIcon, family: 'status', kind: 'system', defaultPalette: 'mono' },
  tentative: { label: 'Tentative', component: TentativeStatusIcon, family: 'status', kind: 'system', defaultPalette: 'mono' },
  info: { label: 'Info', component: InfoIcon, family: 'status', kind: 'system', defaultPalette: 'mono' },
  conflict: { label: 'Conflict', component: AlertIcon, family: 'status', kind: 'system', defaultPalette: 'mono' },
  canceled: { label: 'Canceled', component: BanIcon, family: 'status', kind: 'system', defaultPalette: 'mono' },
  completed: { label: 'Completed', component: StarIcon, family: 'status', kind: 'system', defaultPalette: 'mono' },
  check: { label: 'Check', component: CheckIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  close: { label: 'Close', component: XIcon, family: 'utility', kind: 'system', defaultPalette: 'mono' },
  beachDay: { label: 'Beach Day', component: BeachDayIcon, family: 'activity', kind: 'scene', defaultPalette: 'beach' },
  lakePlankRaft: { label: 'Lake Plank Raft', component: LakePlankRaftIcon, family: 'activity', kind: 'scene', defaultPalette: 'lake' },
  lakeDay: { label: 'Lake Day', component: LakeDayIcon, family: 'activity', kind: 'scene', defaultPalette: 'lake' },
  hiking: { label: 'Hiking', component: HikingIcon, family: 'activity', kind: 'scene', defaultPalette: 'trail' },
  camping: { label: 'Camping', component: CampingIcon, family: 'activity', kind: 'scene', defaultPalette: 'camp' },
  roadTrip: { label: 'Road Trip', component: RoadTripIcon, family: 'activity', kind: 'scene', defaultPalette: 'trail' },
  bbq: { label: 'BBQ', component: BbqIcon, family: 'activity', kind: 'scene', defaultPalette: 'food' },
  picnic: { label: 'Picnic', component: PicnicIcon, family: 'activity', kind: 'scene', defaultPalette: 'food' },
  bikeRide: { label: 'Bike Ride', component: BikeRideIcon, family: 'activity', kind: 'scene', defaultPalette: 'trail' },
  kayaking: { label: 'Kayaking', component: KayakingIcon, family: 'activity', kind: 'scene', defaultPalette: 'water' },
  boating: { label: 'Boating', component: BoatingIcon, family: 'activity', kind: 'scene', defaultPalette: 'lake' },
  poolDay: { label: 'Pool Day', component: PoolDayIcon, family: 'activity', kind: 'scene', defaultPalette: 'water' },
  surfing: { label: 'Surfing', component: SurfingIcon, family: 'activity', kind: 'scene', defaultPalette: 'water' },
  fishing: { label: 'Fishing', component: FishingIcon, family: 'activity', kind: 'scene', defaultPalette: 'water' },
  golf: { label: 'Golf', component: GolfIcon, family: 'activity', kind: 'scene', defaultPalette: 'trail' },
  pickleball: { label: 'Pickleball', component: PickleballIcon, family: 'activity', kind: 'scene', defaultPalette: 'social' },
  tennis: { label: 'Tennis', component: TennisIcon, family: 'activity', kind: 'scene', defaultPalette: 'trail' },
  volleyball: { label: 'Volleyball', component: VolleyballIcon, family: 'activity', kind: 'scene', defaultPalette: 'social' },
  gameNight: { label: 'Game Night', component: GameNightIcon, family: 'activity', kind: 'scene', defaultPalette: 'social' },
  movieNight: { label: 'Movie Night', component: MovieNightIcon, family: 'activity', kind: 'scene', defaultPalette: 'social' },
  pizzaAndDrinks: { label: 'Pizza & Drinks', component: PizzaAndDrinksIcon, family: 'activity', kind: 'scene', defaultPalette: 'food' },
  bonfire: { label: 'Bonfire', component: BonfireIcon, family: 'activity', kind: 'scene', defaultPalette: 'night' },
  coffeeDate: { label: 'Coffee Date', component: CoffeeDateIcon, family: 'activity', kind: 'scene', defaultPalette: 'food' },
  iceCream: { label: 'Ice Cream', component: IceCreamIcon, family: 'activity', kind: 'scene', defaultPalette: 'food' },
  farmersMarket: { label: 'Farmers Market', component: FarmersMarketIcon, family: 'activity', kind: 'scene', defaultPalette: 'food' },
  sunsetWatch: { label: 'Sunset Watch', component: SunsetWatchIcon, family: 'activity', kind: 'scene', defaultPalette: 'night' },
  stargazing: { label: 'Stargazing', component: StargazingIcon, family: 'activity', kind: 'scene', defaultPalette: 'night' },
  concert: { label: 'Concert', component: ConcertIcon, family: 'activity', kind: 'scene', defaultPalette: 'night' },
  museums: { label: 'Museums', component: MuseumsIcon, family: 'activity', kind: 'scene', defaultPalette: 'social' },
  waterPark: { label: 'Water Park', component: WaterParkIcon, family: 'activity', kind: 'scene', defaultPalette: 'water' },
  boardGames: { label: 'Board Games', component: BoardGamesIcon, family: 'activity', kind: 'scene', defaultPalette: 'social' },
  lakeBoatHangout: { label: 'Lake Boat Hangout', component: LakeBoatHangoutIcon, family: 'activity', kind: 'scene', defaultPalette: 'lake' },
} as const satisfies Record<string, AppIconDefinition>

export type AppIconName = keyof typeof ICON_REGISTRY

export const ICON_LIBRARY_SECTIONS: { label: string; icons: AppIconName[] }[] = [
  { label: 'Navigation', icons: ['home', 'calendar', 'sun', 'people', 'messages', 'more'] },
  { label: 'Planning', icons: ['plus', 'time', 'repeat', 'bell', 'category', 'location'] },
  { label: 'Views & Filters', icons: ['listView', 'calendarView', 'filter', 'search', 'sort', 'mapView'] },
  { label: 'Actions', icons: ['edit', 'delete', 'share', 'invite', 'export', 'save'] },
  { label: 'Status', icons: ['confirmed', 'tentative', 'info', 'conflict', 'canceled', 'completed'] },
  {
    label: 'Activities',
    icons: [
      'beachDay',
      'lakePlankRaft',
      'hiking',
      'camping',
      'roadTrip',
      'bbq',
      'picnic',
      'bikeRide',
      'kayaking',
      'boating',
      'poolDay',
      'surfing',
      'fishing',
      'golf',
      'pickleball',
      'tennis',
      'volleyball',
      'gameNight',
      'movieNight',
      'pizzaAndDrinks',
      'bonfire',
      'coffeeDate',
      'iceCream',
      'farmersMarket',
      'sunsetWatch',
      'stargazing',
      'concert',
      'museums',
      'waterPark',
      'boardGames',
    ],
  },
]

export function getIconDefinition(name: AppIconName) {
  return ICON_REGISTRY[name]
}
